-- Seed businesses around ORR Exit 8 / Keesara corridor
-- Sourced from public local listings (schools, hospitals, pumps, shops, civic offices).
-- Phone numbers included only when published; others NULL for later verification.

INSERT INTO public.businesses (
  name, slug, category_id, description, address, phone,
  is_featured, rating, review_count, lat, lng, status
)
SELECT
  b.name, b.slug, c.id, b.description, b.address, b.phone,
  b.is_featured, b.rating, b.review_count, b.lat, b.lng, 'active'::public.business_status
FROM (VALUES
  ('Pallavi International School Keesara', 'pallavi-international-school-keesara', 'education', 'CBSE school campus near Ahmedguda / Bandlaguda in Keesara mandal', 'Plot No. 4-98, Ahmedguda, Keesara Mandal, Hyderabad 501301', '+91 76600 02460', false, 4.5, 120, 17.5205, 78.642),
  ('Davis High School', 'davis-high-school-keesara', 'education', 'Residential school near ORR Exit 8 corridor', 'BBPT Campus, Nehru Outer Ring Road, Godumakunta, Keesara', NULL, false, 4.3, 45, 17.535, 78.648),
  ('TS Residential School Keesaragutta', 'ts-residential-school-keesaragutta', 'education', 'Government residential school near Keesaragutta', 'Keesaragutta, Keesara Mandal', NULL, false, 4.1, 28, 17.545, 78.665),
  ('Geethanjali College of Engineering and Technology', 'geethanjali-college-engineering', 'education', 'Engineering college in Cheeryal village, Keesara mandal', 'Cheeryal Village, Keesara Mandal, Medchal District 501301', NULL, true, 4.2, 210, 17.522, 78.6555),
  ('Geethanjali College of Pharmacy', 'geethanjali-college-pharmacy', 'education', 'Pharmacy college near Cheeryal / Keesara', 'Cheryaal, Secunderabad 501301', NULL, false, 4.0, 55, 17.523, 78.656),
  ('Holy Mary Institute of Technology & Science', 'holy-mary-institute', 'education', 'Engineering & technology institute near Exit 8 corridor', 'Near Keesara / Bogaram road', NULL, false, 3.9, 80, 17.54, 78.67),
  ('Gowthami Junior College & Defence Academy', 'gowthami-junior-college', 'education', 'Junior college and defence academy near Keesara', 'Near ORR Exit 8, Keesara', NULL, false, 4.1, 40, 17.53, 78.65),
  ('KLR Junior College', 'klr-junior-college', 'education', 'Junior college on ECIL–Keesara Road', 'ECIL - Keesara Rd, Kundanpally, Secunderabad', NULL, false, 4.0, 35, 17.515, 78.625),
  ('Sai Pranavi College of Pharmacy', 'sai-pranavi-college-pharmacy', 'education', 'Pharmacy college at Godumakunta', 'Godumakunta, Secunderabad 501301', NULL, false, 3.8, 22, 17.532, 78.645),
  ('Reqelford International School', 'reqelford-international-school', 'education', 'International school serving Exit 8 / Keesara families', 'Near Yadgarpally / Keesara corridor', NULL, false, 4.4, 90, 17.538, 78.66),
  ('Serenity High School', 'serenity-high-school', 'education', 'High school within short drive of Keesara ORR junction', 'Near Keesara', NULL, false, 4.0, 30, 17.525, 78.64),
  ('Vardhana School', 'vardhana-school', 'education', 'School near Kundanpally on ECIL–Keesara Road', 'Kundanpally, Secunderabad 501301', NULL, false, 3.9, 18, 17.512, 78.622),
  ('Arundhathi Vidyalaya High School', 'arundhathi-vidyalaya', 'education', 'High school near Shamirpet–Keesara Road', 'Near Keesara, Hyderabad', NULL, false, 4.0, 25, 17.5355, 78.638),
  ('ZPHS Yadgarpally', 'zphs-yadgarpally', 'education', 'Government Zilla Parishad High School, Yadgarpally', 'Yadgarpally East, Keesara Mandal 501301', NULL, false, 3.7, 15, 17.54, 78.652),
  ('ZPHS Cheeryal', 'zphs-cheeryal', 'education', 'Government high school, Cheeryal village', 'Cheeriyal, Keesara Mandal 501301', NULL, false, 3.6, 12, 17.521, 78.658),
  ('St Joseph''s Model School Dammaiguda', 'st-josephs-model-school-dammaiguda', 'education', 'Model school near Dammaiguda / Keesara block', 'Dammaiguda, Secunderabad', NULL, false, 4.1, 40, 17.505, 78.615),
  ('Rushi High School Nagaram', 'rushi-high-school-nagaram', 'education', 'Private high school in Nagaram, Keesara block', 'Nagaram, Keesara Block, Ranga Reddy', NULL, false, 3.8, 20, 17.5, 78.61),
  ('Pudami English Medium School Nagaram', 'pudami-english-school-nagaram', 'education', 'English medium school in Nagaram', 'Nagaram, Keesara', NULL, false, 3.9, 16, 17.498, 78.608),
  ('NALSAR University of Law', 'nalsar-university-of-law', 'education', 'National law university near Shameerpet / Exit 8 access', 'Justice City, Shameerpet, Hyderabad', NULL, true, 4.6, 320, 17.56, 78.63),
  ('BITS Pilani Hyderabad Campus', 'bits-pilani-hyderabad', 'education', 'BITS Pilani Hyderabad campus near Jawahar Nagar / Exit 8 access', 'Jawahar Nagar, Shameerpet, Hyderabad', NULL, true, 4.7, 500, 17.545, 78.575),
  ('Nithin Hospital', 'nithin-hospital', 'healthcare', 'Multi-specialty hospital near Keesara / Exit 8', 'Near Keesara ORR corridor', NULL, true, 4.2, 85, 17.5285, 78.6485),
  ('Sai Rushi Hospital', 'sai-rushi-hospital', 'healthcare', 'Hospital close to Keesara junction', 'Near Keesara, Hyderabad', NULL, false, 4.1, 60, 17.529, 78.649),
  ('Primary Health Centre Keesara', 'phc-keesara', 'healthcare', 'Government PHC near Keesara Police Station', 'Near Police Station, Keesara 501301', NULL, false, 3.5, 40, 17.527, 78.651),
  ('Keesara Government Hospital', 'keesara-government-hospital', 'healthcare', 'Government hospital serving Keesara mandal', 'Keesara, Medchal-Malkajgiri', NULL, false, 3.6, 55, 17.5265, 78.6525),
  ('Amruth Childrens Clinic', 'amruth-childrens-clinic', 'healthcare', 'Children''s clinic on Dayara Road, Keesara', 'Dayara Road, Keesara, Hyderabad 501301', NULL, false, 4.3, 70, 17.5288, 78.6535),
  ('Ananya Children Clinic and Hospital', 'ananya-children-clinic', 'healthcare', 'Pediatric clinic and hospital near Keesara', 'Keesara, Hyderabad', NULL, false, 4.0, 35, 17.5305, 78.6545),
  ('Sri Sai Thirumala Clinic', 'sri-sai-thirumala-clinic', 'healthcare', 'General clinic in Keesara town', 'Keesara, Hyderabad 501301', NULL, false, 3.9, 28, 17.5275, 78.655),
  ('Srinivasa Medical & General Store', 'srinivasa-medical-store', 'healthcare', 'Medical and general store on Dayara Road', '#1-81, Dayara Road, Keesara, Hyderabad 501301', NULL, false, 4.2, 45, 17.5282, 78.6538),
  ('Sri Sai Kesari Medical & General Stores', 'sri-sai-kesari-medical', 'healthcare', 'Pharmacy and general store on Dayara Road', 'Dayara Road, Keesara, Hyderabad 501301', NULL, false, 4.1, 38, 17.528, 78.654),
  ('Sri Santoshi Medical & General Stores', 'sri-santoshi-medical', 'healthcare', 'Medical store near Ghatkesar–Keesara road', 'Near Keesara–Bogaram–Ghatkesar Road', NULL, false, 4.0, 22, 17.518, 78.668),
  ('Thulasi Hospital ECIL', 'thulasi-hospital-ecil', 'healthcare', 'Hospital at ECIL X Roads (short drive from Exit 8)', 'ECIL X Roads, Hyderabad', NULL, false, 4.3, 150, 17.47, 78.57),
  ('ESI Hospital Nacharam area access', 'esi-hospital-access', 'healthcare', 'ESI hospital accessible from Keesara / ECIL corridor', 'Near ECIL / Nacharam side', NULL, false, 3.8, 90, 17.455, 78.555),
  ('Sri Sai Hari Hara Estates', 'sri-sai-hari-hara-estates', 'real-estate', 'Developer of Vasant Villas near Keesara ORR Junction', 'Harihara Estate, Opp. ISI, St. No. 8, Habsiguda, Hyderabad', '+91 90668 32832', true, 4.4, 65, 17.532, 78.6505),
  ('Vasant Villas by Hari Hara', 'vasant-villas-hari-hara', 'real-estate', '4BHK triplex villas near Keesara ORR Junction', 'Keesara ORR Junction, Hyderabad', '+91 90668 32832', true, 4.5, 48, 17.533, 78.6515),
  ('DIVI Infra Developers', 'divi-infra-developers', 'real-estate', 'Developer of Divi Meadows near Exit 8 / Yadgarpally', 'Near Yadgarpalli Junction, Keesara 100 Feet Road', NULL, true, 4.3, 55, 17.536, 78.658),
  ('Divi Meadows', 'divi-meadows', 'real-estate', 'HMDA & RERA approved villa plots near Exit 8 service road', 'Yadgarpalli Junction, Keesara 100 Feet Road facing', NULL, true, 4.4, 40, 17.5365, 78.6585),
  ('Katipally Estates', 'katipally-estates', 'real-estate', 'Real estate on Shamirpet–Keesara Road, Cheeriyal', 'Shamirpet - Keesara Rd, Cheeriyal 501301', NULL, false, 4.0, 25, 17.5255, 78.657),
  ('SWARGAM Farms', 'swargam-farms', 'real-estate', 'Farm / open plot listings on ECIL–Keesara Road', 'ECIL - Keesara Rd, Keesara 501301', NULL, false, 3.9, 18, 17.531, 78.6455),
  ('Lotus Homes Bandlaguda', 'lotus-homes-bandlaguda', 'real-estate', 'Residential community near Pallavi School / Bandlaguda Keesara', 'Bandlaguda, Ahmedguda, Keesara 501301', NULL, false, 4.1, 70, 17.518, 78.635),
  ('Keesara Plots & Layouts Hub', 'keesara-plots-layouts-hub', 'real-estate', 'Local plot brokers serving ORR Exit 8 corridor', 'Keesara Main Road, Hyderabad 501301', NULL, false, 3.8, 30, 17.528, 78.652),
  ('Yadgarpally Open Plots', 'yadgarpally-open-plots', 'real-estate', 'Open residential plots around Yadgarpally junction', 'Yadgarpally, Keesara Mandal 501301', NULL, false, 3.9, 22, 17.539, 78.653),
  ('Ahmedguda Villa Projects', 'ahmedguda-villa-projects', 'real-estate', 'Villa and gated community projects near Ahmedguda', 'Ahmedguda, Keesara Mandal', NULL, false, 4.0, 28, 17.52, 78.64),
  ('Sri Surya Rohith Family Dhaba', 'sri-surya-rohith-family-dhaba', 'food-retail', 'Family dhaba on Keesaragutta Main Road', 'Keesaragutta Main Road, Beside Registration Office, Keesara 501301', NULL, false, 4.2, 95, 17.5295, 78.6565),
  ('Friends Family Dhaba', 'friends-family-dhaba', 'food-retail', 'Family dhaba at Godumakunta', 'Godumakunta, Secunderabad 501301', NULL, false, 4.0, 60, 17.5335, 78.646),
  ('Chillies Restaurant & Dhaba', 'chillies-restaurant-dhaba', 'food-retail', 'Restaurant and dhaba at Godumakunta', 'Godumakunta, Secunderabad 501301', NULL, false, 4.1, 75, 17.5338, 78.6462),
  ('Chillies RED AC Family Restaurant', 'chillies-red-ac-restaurant', 'food-retail', 'AC family restaurant at Godumakunta', 'Godumakunta, Secunderabad 501301', NULL, false, 4.2, 80, 17.534, 78.6465),
  ('Hotel Yadgarpally X Roads', 'hotel-yadgarpally-x-roads', 'food-retail', 'Hotel / lodge near Yadgarpally crossroads', 'Chiryala Village, Cheeriyal 501301', NULL, false, 3.7, 35, 17.536, 78.65),
  ('BR Plaza Cheeriyal', 'br-plaza-cheeriyal', 'food-retail', 'Local commercial plaza at Cheeriyal', 'Cheryaal, Secunderabad 501301', NULL, false, 3.8, 20, 17.524, 78.6565),
  ('Venkata Narayana Kiranam', 'venkata-narayana-kiranam', 'food-retail', 'Kirana store on Yadgarpally Main Road', 'Yadgarpally Main Road, Yadgarpalle East 501301', NULL, false, 4.3, 50, 17.5405, 78.6525),
  ('Lakshmi Kirana Store', 'lakshmi-kirana-store', 'food-retail', 'Kirana on ECIL–Keesara Road, Kundanpally', '62, ECIL - Keesara Rd, Kundanpally', NULL, false, 4.1, 40, 17.513, 78.623),
  ('Shri Chittharamma Chicken Centre', 'shri-chittharamma-chicken', 'food-retail', 'Chicken / meat shop at Yadgarpally', 'Yadgarpalle East 501301', NULL, false, 4.0, 30, 17.541, 78.6528),
  ('La Fiesta at Exit-8', 'la-fiesta-exit-8', 'food-retail', 'Resort / event venue near ORR Exit 8', 'Near ORR Exit 8, Keesara', NULL, true, 4.3, 110, 17.535, 78.66),
  ('Rustic Vogue', 'rustic-vogue', 'food-retail', 'Resort near ORR Exit 8 Keesara (ECIL side)', 'Near Exit 8, Keesara corridor', NULL, false, 4.2, 70, 17.537, 78.662),
  ('Leonia Holistic Destination', 'leonia-holistic-destination', 'food-retail', 'Resort and entertainment destination near Shamirpet (Exit 8 access)', 'Bommarasipet, Shamirpet, Secunderabad', NULL, true, 4.5, 400, 17.555, 78.62),
  ('Keesara Vegetable Market', 'keesara-vegetable-market', 'food-retail', 'Local vegetable and produce market near bus stand', 'Near Keesara Bus Stand, Keesara 501301', NULL, false, 4.0, 55, 17.5278, 78.6518),
  ('ORR Exit 8 Fresh Mart', 'orr-exit-8-fresh-mart', 'food-retail', 'Neighborhood grocery serving Exit 8 residents', 'Keesara Main Road near ORR Exit 8', NULL, false, 4.1, 42, 17.5315, 78.6495),
  ('Ahmedguda Super Market', 'ahmedguda-super-market', 'food-retail', 'Local supermarket near Ahmedguda / Bandlaguda', 'Ahmedguda, Keesara Mandal 501301', NULL, false, 3.9, 28, 17.5195, 78.6385),
  ('Nagaram Daily Needs', 'nagaram-daily-needs', 'food-retail', 'Daily needs and provisions store in Nagaram', 'Nagaram, near Keesara block', NULL, false, 3.8, 18, 17.499, 78.609),
  ('PGK Clean Air Systems', 'pgk-clean-air-systems', 'home-services', 'Air systems / HVAC services at Ahmedguda', '54/10, Rajiv Gruhakalpa Rd, Ahmedguda, Keesara 501301', NULL, false, 4.0, 25, 17.521, 78.641),
  ('Sree Sai Security Systems', 'sree-sai-security-systems', 'home-services', 'Security systems installer serving east Hyderabad / Keesara', 'Serving Keesara & Boduppal corridor', NULL, false, 3.9, 20, 17.52, 78.63),
  ('KGN Bike Shop', 'kgn-bike-shop', 'home-services', 'Two-wheeler sales and service at Kundanpally', 'Kundanpally, Secunderabad 501301', NULL, false, 4.0, 35, 17.5125, 78.624),
  ('Subham Enterprises', 'subham-enterprises', 'home-services', 'Local services on ECIL–Keesara Road', '62, ECIL - Keesara Rd, Kundanpally', NULL, false, 3.8, 15, 17.5135, 78.6235),
  ('Keesara Plumbing & Electricals', 'keesara-plumbing-electricals', 'home-services', 'Home plumbing and electrical repairs in Keesara town', 'Keesara village, 501301', NULL, false, 4.2, 40, 17.5285, 78.6548),
  ('ORR Exit 8 Packers & Movers', 'orr-exit8-packers-movers', 'home-services', 'Local shifting services for Exit 8 gated communities', 'Near Keesara ORR Exit 8', NULL, false, 3.9, 22, 17.5325, 78.6508),
  ('Yadgarpally Water Suppliers', 'yadgarpally-water-suppliers', 'home-services', 'Tanker and RO water supply for Yadgarpally / Keesara', 'Yadgarpally, Keesara Mandal', NULL, false, 4.0, 30, 17.54, 78.654),
  ('Cheeriyal Welding Works', 'cheeriyal-welding-works', 'home-services', 'Welding and fabrication near Cheeriyal', 'Cheeriyal, Keesara Mandal 501301', NULL, false, 3.7, 12, 17.5225, 78.6575),
  ('Ahmedguda Interior Works', 'ahmedguda-interior-works', 'home-services', 'Interior and carpentry for new villas near Ahmedguda', 'Ahmedguda, Keesara', NULL, false, 4.1, 18, 17.5208, 78.6395),
  ('Keesara Pest Control', 'keesara-pest-control', 'home-services', 'Residential pest control across Keesara mandal', 'Keesara Main Road', NULL, false, 4.0, 25, 17.5272, 78.6522),
  ('Keesara Police Station', 'keesara-police-station', 'civic', 'Local police station on ECIL–Keesara Road', 'ECIL - Keesara Road, Keesara, Medchal District 501301', NULL, false, 3.5, 40, 17.527, 78.6505),
  ('Mandal Revenue Office Keesara', 'mro-keesara', 'civic', 'Mandal Revenue Office for Keesara', 'Keesara, Secunderabad 501301', NULL, false, 3.4, 20, 17.526, 78.6515),
  ('Keesara Gram Panchayat Office', 'keesara-gram-panchayat', 'civic', 'Local gram panchayat / civic office', 'Keesara Town 501301', NULL, false, 3.3, 10, 17.5268, 78.6528),
  ('Drug Control Administration Medchal', 'drug-control-medchal', 'civic', 'District drug control administration office', 'Godumakunta, Secunderabad 501301', NULL, false, 3.5, 8, 17.5325, 78.6458),
  ('Minorities Welfare Office Medchal Keesara', 'minorities-welfare-keesara', 'civic', 'Minorities welfare office serving Medchal / Keesara', 'Godumakunta, Secunderabad 501301', NULL, false, 3.4, 6, 17.5328, 78.646),
  ('Office of District Collector Medchal-Malkajgiri', 'collector-office-medchal', 'civic', 'District collector office (access via Exit 8 corridor)', 'Medchal-Malkajgiri District', NULL, false, 3.6, 30, 17.63, 78.48),
  ('Keesara Registration Office', 'keesara-registration-office', 'civic', 'Property registration office near Keesaragutta road', 'Near Keesaragutta Main Road, Keesara', NULL, false, 3.5, 25, 17.529, 78.656),
  ('Sri Ramalingeshwara Swamy Temple Keesaragutta', 'sri-ramalingeshwara-temple', 'civic', 'Ancient hilltop Shiva temple at Keesaragutta', 'Keesaragutta, Keesara Mandal', NULL, true, 4.7, 1200, 17.548, 78.668),
  ('Gattu Maisamma Temple Chiryala', 'gattu-maisamma-temple', 'civic', 'Temple on Nehru Outer Ring Road near Chiryala', 'Nehru Outer Ring Road, Chiryala Village, Cheeriyal 501301', NULL, false, 4.4, 80, 17.534, 78.655),
  ('Chirayala Laxmi Narasimha Swamy Temple', 'chirayala-laxmi-narasimha-temple', 'civic', 'Temple in Chiryala village', 'Chiryala Village, Cheeriyal 501301', NULL, false, 4.3, 45, 17.533, 78.654),
  ('Sai Baba Temple Cheeriyal', 'sai-baba-temple-cheeriyal', 'civic', 'Sai Baba temple near Cheeriyal', 'Cheryaal, Secunderabad 501301', NULL, false, 4.5, 60, 17.525, 78.6555),
  ('Keesara Bus Station', 'keesara-bus-station', 'transport', 'TSRTC bus station serving Keesara / Exit 8', 'Near ORR Exit 8, Keesara 501301', NULL, true, 3.8, 90, 17.53, 78.649),
  ('Yadgarpally Bus Stop', 'yadgarpally-bus-stop', 'transport', 'Local bus stop at Yadgarpally East', 'Yadgarpalle East, Telangana 501301', NULL, false, 3.6, 25, 17.5402, 78.6522),
  ('Saryu Service Station IndianOil', 'saryu-service-station', 'transport', '24-hour IndianOil petrol pump in Keesara', 'Sy No 9, Keesara, Hyderabad 501301', NULL, false, 4.1, 55, 17.529, 78.648),
  ('Surya Filling Station IndianOil', 'surya-filling-station', 'transport', '24-hour IndianOil filling station in Keesara', 'Sy No 202/208/210, Keesara, Hyderabad 501301', NULL, false, 4.0, 48, 17.5285, 78.6475),
  ('Sri Lingeswara Filling Station', 'sri-lingeswara-filling-station', 'transport', 'IndianOil filling station in Keesara', 'Sy No 367, Keesara, Hyderabad 501301', NULL, false, 3.9, 30, 17.5275, 78.6465),
  ('Padigeshila Filling Station HP', 'padigeshila-filling-station', 'transport', 'HP petrol pump on Ghatkesar Road, Keesara', 'Survey No 42, Ghatkesar Road, Keesara 501301', NULL, false, 4.0, 40, 17.52, 78.66),
  ('NVR Filling Station HP', 'nvr-filling-station', 'transport', 'HP filling station on Rampally / Cheeriyal road', '125 Rampally–Keesara Road, Cheeriyal 501301', NULL, false, 4.0, 35, 17.5355, 78.651),
  ('Neha Filling Station HP', 'neha-filling-station', 'transport', 'HP petrol pump near Thimmaipally / Dharmaram', 'Thimmaipally Dharmaram Village, Keesara Mandal', NULL, false, 3.9, 28, 17.515, 78.67),
  ('HP Petrol Pump Yadgarpally X Rd', 'hp-petrol-yadgarpally', 'transport', 'HP petrol bunk at Yadgarpally crossroads', 'Yadgarpally X Rd, Chiryala Village, Cheeriyal 501301', NULL, false, 4.1, 50, 17.5362, 78.6502),
  ('Adhoc Vyjayanthi Services HP', 'adhoc-vyjayanthi-services', 'transport', 'HP petrol pump on Cheeriyal–Yadgarpalli Road', 'Cheeriyal Yadgarpalli Road, Keesara 501301', NULL, false, 3.9, 22, 17.5358, 78.6508),
  ('SBI ATM Cheeriyal', 'sbi-atm-cheeriyal', 'civic', 'State Bank of India ATM near Cheeriyal', 'Cheryaal, Secunderabad 501301', NULL, false, 3.8, 15, 17.5245, 78.6562),
  ('ICICI Bank ATM Kundanpally', 'icici-atm-kundanpally', 'civic', 'ICICI Bank ATM at Kundanpally', 'Kundanpally, Secunderabad 500083', NULL, false, 3.9, 12, 17.512, 78.621),
  ('Axis Bank ATM Dammaiguda', 'axis-atm-dammaiguda', 'civic', 'Axis Bank ATM at Dammaiguda / Ramana Nagar', 'Shop No.1, H.No.6-3, Ramana Nagar, Dammaiguda', NULL, false, 3.8, 10, 17.5055, 78.614),
  ('State Bank of India Keesara', 'sbi-keesara', 'civic', 'SBI branch / banking services for Keesara residents', 'Keesara, Hyderabad 501301', NULL, false, 3.7, 35, 17.5275, 78.6512),
  ('Icomm Tele Limited', 'icomm-tele-limited', 'home-services', 'Telecom / industrial facility near Kundanpally', 'Kundanpally, Secunderabad 500083', NULL, false, 3.6, 8, 17.51, 78.62),
  ('Nitya Boys Hostel Cheeriyal', 'nitya-boys-hostel', 'education', 'Boys hostel near Cheeriyal for college students', 'Cheryaal, Secunderabad 501301', NULL, false, 3.7, 20, 17.5255, 78.6558),
  ('Pocharam IT SEZ Access Corridor', 'pocharam-it-sez', 'civic', 'IT SEZ employment hub (Infosys, Genpact) driving Exit 8 demand', 'Pocharam, near ORR east corridor', NULL, true, 4.5, 200, 17.48, 78.68),
  ('Keesara Auto Stand', 'keesara-auto-stand', 'transport', 'Shared auto stand near Keesara bus station', 'Near Keesara Bus Station, 501301', NULL, false, 3.5, 40, 17.5302, 78.6492),
  ('ECIL–Keesara Road Cab Point', 'ecil-keesara-cab-point', 'transport', 'Pickup point for cabs and bike taxis on ECIL–Keesara Road', 'ECIL - Keesara Rd junction area', NULL, false, 3.6, 18, 17.52, 78.63),
  ('Godumakunta Mechanic Shed', 'godumakunta-mechanic', 'transport', 'Two-wheeler and car mechanic near Godumakunta', 'Godumakunta, Keesara', NULL, false, 4.0, 30, 17.533, 78.6455),
  ('Cheeriyal Bike Service', 'cheeriyal-bike-service', 'transport', 'Bike service centre at Cheeriyal', 'Cheeriyal, Keesara Mandal', NULL, false, 3.9, 22, 17.5235, 78.6572),
  ('Sri Sri Holistic Hospitals', 'sri-sri-holistic-hospitals', 'healthcare', 'Multi-specialty hospital providing comprehensive healthcare and emergency services on Nizampet Road', 'Nizampet Road', NULL, true, 4.6, 120, 17.514, 78.388),
  ('SLG Hospitals', 'slg-hospitals', 'healthcare', 'Advanced super-specialty hospital with state-of-the-art medical infrastructure on Bachupally Road', 'Bachupally Road', NULL, true, 4.3, 95, 17.531, 78.375),
  ('Pragathi''s Yoga Center', 'pragathis-yoga-center', 'healthcare', 'Holistic wellness and yoga center offering therapeutic yoga, meditation, and fitness classes', 'Kakatiya Hills', NULL, true, 4.8, 64, 17.442, 78.391),
  ('Veeradhya Properties', 'veeradhya-properties', 'real-estate', 'Premium real estate consultancy and property advisory serving Hill County and surrounding corridors', 'Hill County', NULL, true, 5.0, 48, 17.518, 78.384),
  ('A&I Realty', 'a-and-i-realty', 'real-estate', 'Trusted property management, residential layout advisory, and real estate services in Pragathi Nagar', 'Pragathi Nagar', NULL, true, 5.0, 52, 17.516, 78.39),
  ('Pai International', 'pai-international', 'food-retail', 'Leading electronics, appliances, and retail store chain offering home appliances and digital gadgets', 'Nizampet Colony', NULL, true, 4.8, 180, 17.512, 78.389)
) AS b(name, slug, cat_slug, description, address, phone, is_featured, rating, review_count, lat, lng)
JOIN public.categories c ON c.slug = b.cat_slug
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category_id = EXCLUDED.category_id,
  description = EXCLUDED.description,
  address = EXCLUDED.address,
  phone = COALESCE(EXCLUDED.phone, public.businesses.phone),
  is_featured = EXCLUDED.is_featured,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  lat = EXCLUDED.lat,
  lng = EXCLUDED.lng,
  status = 'active';

-- 100 businesses seeded for Exit 8 / Keesara
